### ISSUE TITLE
Make level an optional parameter

### ISSUE THREAD

**Issue by JackWilb** [visdesignlab/upset-alt-txt-gen#26]
By default, we should show all levels with level 1 information above level 2 information. This should change the function calls so that we no longer need the level parameter, but could provide it if it we just want 1 of the levels

**Comment by elizaan** [comment]
So, _python3 src/alttxt --data data/movie_data_dev_sort.json_ should return the level 1 and level 2 information altogether right? and _python3 src/alttxt --data data/movie_data_dev_sort.json --level 1_ should return level 1 information?
