### ISSUE TITLE
Integrate higher level descriptions of the plot.

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset-alt-txt-gen#27]
We want to integrate the following information that is provided by humans: 

what does the dataset show; `dataset-description`. Example: "Attributes of characters from The Simpsons" 
what are the sets: `set-description` "character attributes" 
what are the items:  `item-description` "characters" 

The figure caption: `caption` "An UpSet plot showing relationships of attributes of Simpsons characters. Notably, the biggest intersection is between Male and School, and between Duff Fan, Male, and PowerPlants, indicating that male non-school children in the Simpsons work at the power plant and like Duff Beer".

**Comment by JakeWags** [comment]
If the user doesn't input these values within Multinet, use generic language e.g Columns, Intersections, etc

**Comment by elizaan** [comment]
@alexsb, @JakeWags, and @JackWilb can we call the below paragraph (copied caption from the issue description) alternative text? or any suggestion how should the alternative text should look like?

"An UpSet plot showing relationships of attributes of Simpsons characters. Notably, the biggest intersection is between Male and School, and between Duff Fan, Male, and PowerPlants, indicating that male non-school children in the Simpsons work at the power plant and like Duff Beer"

**Comment by alexsb** [comment]
Yes, I think that's reasonable if slightly on the long side.
