### ISSUE TITLE
Restructure output to be JSON

### ISSUE THREAD

**Issue by JakeWags** [visdesignlab/upset-alt-txt-gen#30]
API Response:
keys: alt-text, long-description, structured-text

structured-text: return JSON with individual levels. Each level should be structured with nested json.
i.e. 
``` 
{ level1: {
header1: {  
... } 
}
}
 ```
 etc

**Comment by alexsb** [comment]
@elizaan and I reviewed this today; what we probably want is structure but not at a "level" level. 

Here's how this should look, and we want to possibly also format this information: 

=====

## UpSet Introduction
This is an UpSet plot that visualizes set intersection. To learn about UpSet plots, visit upset.app. 

## Dataset Properties
The dataset shows attributes of characters from the Simpsons. It contains 6 sets, and 44 elements, of which 6 sets are shown in the plot. 

## Set Properties
The largest set is Male, with 8 characters, followed by Duff Fan with 6, Evil with 6, School with 6, Power Plant with 5, and Blue Hair with 3.

## Intersection Properties
The plot is sorted by size. There are 12 non-empty intersections, all of which are shown in the plot. The largest 5 intersections are School & Male (3 characters), the empty intersection (3), just Male (3), Duff Fan, Male & Power Plant (3), and Evil & Male (2). 

## Statistical Information
The average intersection size is z, the median is q. The 90th percentile is r, and the 10th percentile is q. The largest set, Male, is present in x% of all non-empty intersections. The smallest set Blue Hair is present in y% of all intersections.

=====

In addition, we want to add a single, very short alt-text line. 

Should the text from above be just in one field and be formatted e.g., with Markdown?

**Comment by JakeWags** [comment]
This looks like a good change!! 😸

**Comment by JakeWags** [comment]
This looks like a good change! 👯‍♂️ 😸
