### ISSUE TITLE
Minor language updates

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset-alt-txt-gen#65]
The largest intersection is ADB, and CERN -> 
The largest intersection is between ADB and Cern
(add between, and ideally remove oxford comma when just 2, but keep when 3)

The largest 5 intersections are Just the empty inter (139), Just ADB -> 
The largest 5 intersections are the empty intersection (139), just ADB
(incorrect "Just"; "inter" should be "intersection; incorrectly capitazlied "Just", and later on there's another oxford comma situation. 
We should also add semicolons between these here, so that it should read: 

The plot is sorted by size in descending order. There are 26 non-empty intersections, all of which are shown in the plot. The largest 5 intersections are the empty intersection (139); Just ADB (23); ADB and CERN (10); ADB and CICA (8); and ADB and APEC (7).

The "Just the empty inter" re-appears later

**Comment by elizaan** [comment]
(add between, and ideally remove the Oxford comma when just 2, but keep when 3)-> adding between is only for the intersection between two sets, right?

**Comment by alexsb** [comment]
between two or more
